# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Parse Blog
description: > # this means to ignore newlines until "baseurl:"
  The best place to stay up-to-date with the latest Parse news and events.
keywords: backend, mobile, development, server, code
baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.parseplatform.org/ # the base hostname & protocol for your site, e.g. http://example.com

# Gems
gems:
  - jekyll-paginate-v2

whitelist:
  - jekyll-paginate-v2

# Build settings
markdown: kramdown
sass:
  sass_dir: css
pagination:
   enabled: true
   per_page: 10
   permalink: /blog/:num/
   sort_field: 'date'
   sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [ Gemfile, Gemfile.lock, README.md, .gitignore ]

# Include you as an author here.
authors:
  flovilmart:
    name: Florent Vilmart
    byline: Core Contributor on Parse
    github: flovilmart
    twitter: flovilmart
    site: http://parseplatform.org/
  montymxb:
    name: Ben Friedman
    byline: Core Contributor on Parse
    github: montymxb
    site: http://parseplatform.org/
  tom-fox1:
    name: Tom Fox
    byline: Parse Fan & Contributor
    github: tom-fox1
    twitter: T0mfox
  # Original Parse Team
  courtneywitmer:
    name: Courtney Witmer
  andrewimm:
    name: Andrew Imm
  foscomarotto:
    name: Fosco Marotto
  bennham:
    name: Ben Nham
  listiarsowastuargo:
    name: Listiarso Wastuargo
  christineyen:
    name: Christine Yen
  beardouglas:
    name: Bear Douglas
  mattieugamacheasselin:
    name: Mattieu Gamache-Asselin
  ashleysmith:
    name: Ashley Smith
  hectorramos:
    name: Héctor Ramos
  abhishekkona:
    name: Abhishek Kona
  christophetauziet:
    name: Christophe Tauziet
  charitymajors:
    name: Charity Majors
  ilyasukhar:
    name: Ilya Sukhar
  grantlandchew:
    name: Grantland Chew
  bryanklimt:
    name: Bryan Klimt
  naitikshah:
    name: Naitik Shah
  nancyxiao:
    name: Nancy Xiao
  kailiu:
    name: Kai Liu
  stanleywang:
    name: Stanley Wang
  christineabernathy:
    name: Christine Abernathy
  jamiekarraker:
    name: Jamie Karraker
  karangajwani:
    name: Karan Gajwani
  thomasbouldin:
    name: Thomas Bouldin
  nikitalutsenko:
    name: Nikita Lutsenko
  georgekedenburgiii:
    name: George Kedenburg III
  devincheevers:
    name: Devin Cheevers
  jamesyu:
    name: James Yu
  parse:
    name: Parse
  mikekania:
    name: Mike Kania
  ronaldyang:
    name: Ronald Yang
  björnkaiser:
    name: Björn Kaiser
  pavanathivarapu:
    name: Pavan Athivarapu
  drewgross:
    name: Drew Gross
  ericnakagawa:
    name: Eric Nakagawa
  vítorfernandes:
    name: Vítor Fernandes
  damiankowalewski:
    name: Damian Kowalewski
  travisredman:
    name: Travis Redman
  mengyanwang:
    name: Mengyan Wang
  georgeyakovlev:
    name: George Yakovlev
  richardross:
    name: Richard Ross
  jakeblakeley:
    name: Jake Blakeley
  kevinlacker:
    name: Kevin Lacker
  patrickpelletier:
    name: Patrick Pelletier
