# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Parse Blog
description: > # this means to ignore newlines until "baseurl:"
  The best place to stay up-to-date with the latest Parse news and events.
keywords: backend, mobile, development, server, code
baseurl: "" # the subpath of your site, e.g. /blog
url: http://blog.parseplatform.org/ # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: css
paginate: 10
paginate_path: "/blog/:num/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude: [ Gemfile, Gemfile.lock, README.md, .gitignore, CNAME ]

# Include you as an author here.
authors:
  davimacedo:
    name: Davi Macedo
    byline: Co-founder at Back4App
    github: davimacedo
    twitter: adavimacedo
    site: https://www.back4app.com
